/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMissoesRouteImport } from './routes/app.missoes'
import { Route as AppPontosRouteImport } from './routes/app.pontos'
import { Route as AppScanRouteImport } from './routes/app.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPontosRoute = AppPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/missoes': typeof AppMissoesRoute
  '/app/pontos': typeof AppPontosRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/pontos': typeof AppPontosRoute
  '/app/scan': typeof AppScanRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/missoes': typeof AppMissoesRoute
  '/app/pontos': typeof AppPontosRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/app' | '/app/missoes' | '/app/pontos' | '/app/scan' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/missoes' | '/app/pontos' | '/app/scan' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/missoes'
    | '/app/pontos'
    | '/app/scan'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missoes': {
      id: '/app/missoes'
      path: '/missoes'
      fullPath: '/app/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pontos': {
      id: '/app/pontos'
      path: '/pontos'
      fullPath: '/app/pontos'
      preLoaderRoute: typeof AppPontosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMissoesRoute: typeof AppMissoesRoute
  AppPontosRoute: typeof AppPontosRoute
  AppScanRoute: typeof AppScanRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMissoesRoute: AppMissoesRoute,
  AppPontosRoute: AppPontosRoute,
  AppScanRoute: AppScanRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
